image: alamaby/flutter:latest

cache:
  key: "${CI_PROJECT_ID}"
  paths:
    - .packages

stages:
  - build

build:android:debug:
  stage: build
  only:
    - master
  script:
    - flutter upgrade
    - flutter clean
    - flutter packages upgrade
    - flutter -v build apk --debug
    - mv build/app/outputs/apk/debug/app-debug.apk build/app/outputs/apk/debug/${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_debug.apk
    
  artifacts:
    name: "${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - build/app/outputs/apk/debug
    expire_in: 4 weeks

build:android:release:
  stage: build
  only:
    - /^v.*$/
  script:
    - flutter upgrade
    - flutter clean
    - flutter packages upgrade
    - flutter -v build apk --release
    - mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.apk
    
  artifacts:
    name: "${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_${CI_COMMIT_TAG}"
    paths:
      - build/app/outputs/apk/release
    expire_in: 4 weeks
